#!/bin/sh

echo -e "\n>>>>>>>>>>>> Run Rootfs rcS <<<<<<<<<<<<\n"

chown root:root /var/empty
chmod 700 /var/empty

# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do
    # echo -e "\n>>>>>>>>>>>> Run $i <<<<<<<<<<<<\n"

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done
