#!/bin/sh

bootmedium=emmc

linkdev() {
    if [ ! -d "/dev/block/by-name" ];then
        mkdir -p /dev/block/by-name
        cd /dev/block/by-name
        ln -sf /dev/mmcblk0p1 env
        ln -sf /dev/mmcblk0p2 idblock
        ln -sf /dev/mmcblk0p3 uboot
        ln -sf /dev/mmcblk0p4 boot
        ln -sf /dev/mmcblk0p5 rootfs
        ln -sf /dev/mmcblk0p6 oem
        ln -sf /dev/mmcblk0p7 userdata
    fi
}

mount_part() {
    partname=$1
    part_fstype=$2
    mountpt=$3

    part_dev=/dev/block/by-name/$partname
    e2fsck -y ${part_dev}
    mount -t ${part_fstype} ${part_dev} ${mountpt}
    if [ $? -eq 0 ]; then
        resize2fs $part_dev
        tune2fs $part_dev -L $partname
    else
        echo "mount $partname error, try to format..."
        mke2fs -F -L $partname $part_dev
        tune2fs -c 0 -i 0 $part_dev
        mount -t $part_fstype $part_dev $mountpt
    fi
}

case $1 in
    start)
        linkdev
        mount_part userdata ext4 /userdata ext4
        mount_part oem ext4 /oem ext4
        ;;
    linkdev)
        linkdev ;
        ;;
    stop)
        printf "stop $0 finished\n"
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
    esac
