#!/bin/sh

[ -f /etc/profile.d/SSEnv.sh ] && source /etc/profile.d/SSEnv.sh

function enable_coredump()
{
    ulimit -c unlimited
    echo "/userdata/core-%p-%e" > /proc/sys/kernel/core_pattern
}

case $1 in
    start)
        /etc/init.d/connect_net.sh &
        enable_coredump
        [ ! -f /oem/etc/init.d/rcS ] || sh /oem/etc/init.d/rcS
        [ ! -f /system/bin/show_ipaddr ] || /system/bin/show_ipaddr &
        ;;
    stop)
        sync
        ;;
    *)
        exit 1
        ;;
esac
