#!/bin/sh
cmd=`realpath $0`
_DIR=`dirname $cmd`

case $1 in
    start)
        # cd /userdata
        # ./00_myipc &
        ;;
    stop)
        sync
        ;;
    *)
        exit 1
        ;;
esac
